#!/usr/bin/env bash
set -euo pipefail

PROFILE="core"
PYTHON_BIN="python3"
VENV_DIR=".venv"
RELOCK=0
SKIP_CHECKS=0

usage() {
  cat <<'EOF'
Usage: scripts/bootstrap_env.sh [options]

Options:
  --profile <core|ml|full-stack>  Dependency profile to install (default: core)
  --python <python-bin>           Python executable to create the venv (default: python3)
  --venv <path>                   Virtual environment path (default: .venv)
  --relock                        Regenerate lockfile from installed environment
  --skip-checks                   Skip dependency checker run
  -h, --help                      Show this help message

Examples:
  scripts/bootstrap_env.sh --profile core
  scripts/bootstrap_env.sh --profile full-stack --relock
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --python)
      PYTHON_BIN="$2"
      shift 2
      ;;
    --venv)
      VENV_DIR="$2"
      shift 2
      ;;
    --relock)
      RELOCK=1
      shift
      ;;
    --skip-checks)
      SKIP_CHECKS=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

case "$PROFILE" in
  core|ml|full-stack) ;;
  *)
    echo "Invalid profile '$PROFILE'. Expected: core, ml, or full-stack."
    exit 1
    ;;
esac

REQ_FILE="requirements/profiles/${PROFILE}.txt"

if [[ ! -d "$VENV_DIR" ]]; then
  echo "Creating virtual environment at $VENV_DIR"
  "$PYTHON_BIN" -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1090
source "$VENV_DIR/bin/activate"

PY_TAG=$(python - <<'PY'
import sys
print(f"py{sys.version_info.major}{sys.version_info.minor}")
PY
)

if [[ "$PY_TAG" == "py311" ]]; then
  LOCK_FILE="requirements/locks/${PROFILE}-py311.lock"
else
  LOCK_FILE="requirements/locks/${PROFILE}.lock"
fi

if [[ ! -f "$REQ_FILE" ]]; then
  echo "Missing requirements profile: $REQ_FILE"
  exit 1
fi

python -m pip install --upgrade pip setuptools wheel

if [[ -f "$LOCK_FILE" && "$RELOCK" -eq 0 ]]; then
  echo "Installing from lockfile: $LOCK_FILE"
  python -m pip install -r "$LOCK_FILE"
else
  echo "Installing from profile: $REQ_FILE"
  python -m pip install -r "$REQ_FILE"

  echo "Writing lockfile: $LOCK_FILE"
  {
    echo "# Auto-generated by scripts/bootstrap_env.sh"
    echo "# Profile: $PROFILE"
    echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    python -m pip freeze --all | LC_ALL=C sort
  } > "$LOCK_FILE"
fi

if [[ "$SKIP_CHECKS" -eq 0 ]]; then
  echo "Running dependency checks for profile: $PROFILE"
  python scripts/check_packages.py --profile "$PROFILE"
fi

echo "Bootstrap complete."
echo "Activate with: source $VENV_DIR/bin/activate"
